
version: '3'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - .:/application
          - ./dockercc/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=db_user
          - MYSQL_PASSWORD=root
          - MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
        ports:
          - "3306:3306"
  website:
    container_name: php74
    image: cc:php_img
    build:
      context: ./
    volumes:
      - ./dockercc:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - mysql
